/**
 * Figma Community resources.
 *
 * Covers are self-hosted under /public/shots/figma/. Figma's CDN returns 403 to
 * any request that is not from figma.com, so the original URLs cannot be
 * hotlinked or run through the image optimiser.
 *
 * Entered by hand — Figma exposes no public API for Community profiles and the
 * profile page blocks automated fetches, so this is the one source on the site
 * that cannot be regenerated by a script. Scraped from the live profile on
 * 2026-08-15; refresh the counts by hand when they matter.
 *
 * `year` is derived from Figma's relative "Last updated" label, which is all it
 * shows publicly, so treat it as approximate.
 */

export type FigmaResource = {
  slug: string
  title: string
  /** Short description in our own words, not Figma's marketing copy. */
  blurb: string
  url: string
  cover: string
  category: string
  /** Approximate, from a relative timestamp. */
  year: string
  likes: number
  /** Figma calls these "users" — the number of people who duplicated the file. */
  duplicates: number
  tags: string[]
  license: 'CC BY 4.0'
  /** Built as a practice brief for developers to clone and build against. */
  devResource: boolean
}

export const FIGMA_RESOURCES: FigmaResource[] = [
  {
    slug: 'event-ticket-booking-ui',
    title: 'Event Ticket Booking UI',
    blurb:
      'A three-step, login-free ticket booking flow built as a practice brief. Ships with a component breakdown and a spec covering state management, file uploads, payment webhooks and QR validation, so frontend and backend developers can each take a slice.',
    url: 'https://www.figma.com/community/file/1470800949188681164/event-ticket-booking-ui-open-source-practice-project',
    cover:
      '/shots/figma/event-ticket-booking-ui.webp',
    category: 'Software development',
    year: '2024',
    likes: 53,
    duplicates: 1500,
    tags: ['frontend', 'backend', 'practice', 'free template'],
    license: 'CC BY 4.0',
    devResource: true,
  },
  {
    slug: 'tailwind-design-system',
    title: 'Fully Editable Tailwind Design System',
    blurb:
      'A Tailwind-aligned design system with local variables wired through it, so tokens change in one place. The most duplicated file on the profile.',
    url: 'https://www.figma.com/community/file/1350467200753119300/full-editable-tailwind-design-system-plus-local-variables',
    cover:
      '/shots/figma/tailwind-design-system.webp',
    category: 'Libraries',
    year: '2024',
    likes: 39,
    duplicates: 1800,
    tags: ['design system', 'responsive', 'style guide', 'ui kit'],
    license: 'CC BY 4.0',
    devResource: true,
  },
  {
    slug: 'wedding-invitations',
    title: 'Wedding Invitations + Editable Assets',
    blurb:
      'A set of editable wedding invitation layouts and assets, published so other designers could pick up a starting point rather than begin from a blank page.',
    url: 'https://www.figma.com/community/file/1250114761474463959/wedding-invitations-editable-assets',
    cover:
      '/shots/figma/wedding-invitations.webp',
    category: 'Print',
    year: '2023',
    likes: 9,
    duplicates: 1300,
    tags: ['print', 'invitations', 'editable'],
    license: 'CC BY 4.0',
    devResource: false,
  },
  {
    slug: 'creatives-paykit',
    title: "Creative's Paykit 2.0",
    blurb:
      'Quotation, invoice and contract templates for freelancers — the paperwork side of creative work, laid out so it can be edited and sent the same day.',
    url: 'https://www.figma.com/community/file/1279175705868480452/creatives-paykit-2-0-free',
    cover:
      '/shots/figma/creatives-paykit.webp',
    category: 'Templates',
    year: '2023',
    likes: 18,
    duplicates: 308,
    tags: ['invoice', 'quotation', 'receipt', 'template'],
    license: 'CC BY 4.0',
    devResource: false,
  },
  {
    slug: 'drop-shadow-calculation',
    title: 'Mastering Drop Shadow Calculation',
    blurb:
      'A teaching file on how drop shadows are actually calculated in Figma — offset, blur and spread as a system rather than guesswork. Paired with a YouTube walkthrough.',
    url: 'https://www.figma.com/community/file/1350482948856438867/mastering-drop-shadow-calculation',
    cover:
      '/shots/figma/drop-shadow-calculation.webp',
    category: 'Education',
    year: '2024',
    likes: 3,
    duplicates: 247,
    tags: ['tutorial', 'drop shadow', 'style guide', 'guide'],
    license: 'CC BY 4.0',
    devResource: false,
  },
  {
    slug: 'expense-tracker-app',
    title: 'Expense Tracker App',
    blurb:
      'A personal finance app UI published as a clonable practice project, in the same dev-mode-ready format as the ticket booking brief.',
    url: 'https://www.figma.com/community/file/1628277359475428326/expense-tracker-app',
    cover:
      '/shots/figma/expense-tracker-app.webp',
    category: 'Software development',
    year: '2026',
    likes: 4,
    duplicates: 171,
    tags: ['free', 'mobile', 'practice'],
    license: 'CC BY 4.0',
    devResource: true,
  },
  {
    slug: 'social-media-video-streaming-app',
    title: 'Social Media Video Streaming App',
    blurb:
      'A streaming app UI built as a free developer resource for HNG12 and open to any bootcamp, spanning mobile and web and deliberately framework-agnostic.',
    url: 'https://www.figma.com/community/file/1476241019808414751/social-media-video-streaming-app-free-dev-resource',
    cover:
      '/shots/figma/social-media-video-streaming-app.webp',
    category: 'Software development',
    year: '2025',
    likes: 2,
    duplicates: 37,
    tags: ['dev resource', 'mobile', 'web', 'hng'],
    license: 'CC BY 4.0',
    devResource: true,
  },
]

/** Duplicates across every published file — the honest headline number. */
export const FIGMA_TOTAL_DUPLICATES = FIGMA_RESOURCES.reduce((n, r) => n + r.duplicates, 0)
